DROP TABLE IF EXISTS `xfx_block_histories`;
CREATE TABLE `xfx_block_histories` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
    `tx_id` varchar(128) DEFAULT 'mass' COMMENT '交易ID,交易HASH',
    `block_height` bigint NOT NULL COMMENT '爆块时区块高度',
    `height_spent` varchar(58) DEFAULT NULL COMMENT '忽略',
    `block_time` BIGINT DEFAULT NULL COMMENT '爆块时间(超过12个小时，才会到账)',
    `time_str` varchar(58) DEFAULT 'COINBASE' COMMENT '爆块时间字符串',
    `block_type` varchar(58) DEFAULT 'COINBASE' COMMENT '爆块类型',
    `amount` decimal(55, 12) DEFAULT '0' COMMENT '获得了几个xfx:爆块1个块等于64个mass币,分配到了多少个币',
    `amount_text` varchar(188) DEFAULT NULL COMMENT '获得了几个xfx:文本模式爆块1个块等于64个mass币,分配到了多少个币',
    `amount_mojo` varchar(188) DEFAULT NULL COMMENT '获得了几个xfx:文本模式爆块1个块等于64个mass币,分配到了多少个币',
    `pool_id` bigint NOT NULL DEFAULT 0 COMMENT '矿池ID',
    `pool_name` varchar(188) DEFAULT NULL COMMENT '矿池名:mass-A,mass-B',
    `pool_type` varchar(128) DEFAULT NULL COMMENT '矿池类型币种类型：bzz、pha、chia、mass等',
    `groover_id` bigint NOT NULL DEFAULT 0 COMMENT '矿工号ID',
    `pool_order` INT DEFAULT 0 COMMENT '矿工所在的矿池排序',
    `groover` varchar(128) DEFAULT NULL COMMENT '矿工名,选填',
    `wallet_id` varchar(150) default null COMMENT '矿池钱包ID-应该理解为矿工号-对应矿机',
    `wallet_address` varchar(150) default null COMMENT '矿池钱包地址',
    `status` tinyint(2) NOT NULL DEFAULT 0 COMMENT '是否分币（0未分币，1已分币）',
    `modify` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '修改时间',
    `create_time` datetime NOT NULL DEFAULT current_timestamp() COMMENT '插表创建时间',
    PRIMARY KEY (`id`),
    KEY `pool_id` (`pool_id`),
    KEY `groover_id` (`groover_id`),
    KEY `block_time` (`block_time`),
    KEY `wallet_address` (`wallet_address`),
    KEY `status` (`status`),
    KEY `tx_id` (`tx_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT = 'xfx爆块日志表';